/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CostSavingsRouteImport } from './routes/cost-savings'
import { Route as LeakDetectionRouteImport } from './routes/leak-detection'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CostSavingsRoute = CostSavingsRouteImport.update({
  id: '/cost-savings',
  path: '/cost-savings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeakDetectionRoute = LeakDetectionRouteImport.update({
  id: '/leak-detection',
  path: '/leak-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RoomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cost-savings': typeof CostSavingsRoute
  '/leak-detection': typeof LeakDetectionRoute
  '/monitoring': typeof MonitoringRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cost-savings': typeof CostSavingsRoute
  '/leak-detection': typeof LeakDetectionRoute
  '/monitoring': typeof MonitoringRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/cost-savings': typeof CostSavingsRoute
  '/leak-detection': typeof LeakDetectionRoute
  '/monitoring': typeof MonitoringRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/cost-savings'
    | '/leak-detection'
    | '/monitoring'
    | '/rooms'
    | '/settings'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/cost-savings'
    | '/leak-detection'
    | '/monitoring'
    | '/rooms'
    | '/settings'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/cost-savings'
    | '/leak-detection'
    | '/monitoring'
    | '/rooms'
    | '/settings'
    | '/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CostSavingsRoute: typeof CostSavingsRoute
  LeakDetectionRoute: typeof LeakDetectionRoute
  MonitoringRoute: typeof MonitoringRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-savings': {
      id: '/cost-savings'
      path: '/cost-savings'
      fullPath: '/cost-savings'
      preLoaderRoute: typeof CostSavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leak-detection': {
      id: '/leak-detection'
      path: '/leak-detection'
      fullPath: '/leak-detection'
      preLoaderRoute: typeof LeakDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof RoomsRoute
    }
  }
}

interface RoomsRouteChildren {
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  CostSavingsRoute: CostSavingsRoute,
  LeakDetectionRoute: LeakDetectionRoute,
  MonitoringRoute: MonitoringRoute,
  RoomsRoute: RoomsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
